### ISSUE TITLE
Building with CMake on Windows

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/graphviz-feedstock#11]
Recent development in `master` has resulted in inclusion and testing of a CMake-based build system. This will greatly simplify the work needed to build Graphviz from source on Windows. Thus it should be feasible for us to approach on the next Graphviz release that constrains CMake support. Am opening this issue as a reminder of this when it comes to package the next Graphviz release.

**Comment by ccordoba12** [comment]
+1 to this!

**Comment by jakirkham** [comment]
It would be good to check if this works on the latest release now that PR ( https://github.com/conda-forge/graphviz-feedstock/pull/41 ) has landed.

**Comment by jakirkham** [comment]
Maybe this can be handled as part of upgrading to the latest version?

https://github.com/conda-forge/graphviz-feedstock/issues/46

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 )! 😀
