### ISSUE TITLE
unable to create DAG

### ISSUE THREAD

**Issue by HIM72** [conda-forge/graphviz-feedstock#16]
I installed snakemake through miniconda3 and got following error when I run 

` snakemake --dag sorted_reads/{A,B}.bam.bai | dot -Tsvg > dag.svg`
> dot: error while loading shared libraries: libcgraph.so.6: cannot open shared object file: No such file or directory
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

 my OS info where I am getting the error is below
>LSB Version:	:core-3.1-amd64:core-3.1-ia32:core-3.1-noarch:graphics-3.1-amd64:graphics-3.1-ia32:graphics-3.1-noarch
>Distributor ID:	RedHatEnterpriseServer
>Description:	Red Hat Enterprise Linux Server release 5.4 (Tikanga)
>Release:	5.4
>Codename:	Tikanga

**Comment by ccordoba12** [comment]
Conda-forge packages only work on CentOS 6 or newer, sorry.

**Comment by HIM72** [comment]
Is there another way to get around this ?

**Comment by ccordoba12** [comment]
Use the default packages, which are still compiled in CentOS 5.

**Comment by apoudel20** [comment]
I'm facing the same issue and my OS info is:
```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 7.6 (Maipo)
Release:	7.6
Codename:	Maipo
```
Should I also resort to using the default packages?
