### ISSUE TITLE
Upgrading to 2.40.1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/graphviz-feedstock#21]
The 2.40 release series includes a number of improvements. One of these is Windows support using CMake. Would be good to upgrade to this version. Should hopefully simplify our maintenance burden here and resolve issue ( https://github.com/conda-forge/graphviz-feedstock/issues/11 ).

**Comment by kalefranz** [comment]
2.40.1 is from Dec 2016 :(

**Comment by mariusvniekerk** [comment]
Depends on https://github.com/conda-forge/staged-recipes/pull/7079

**Comment by peterjc** [comment]
@marcelotrevisani That's been merged.

**Comment by zhihaoy** [comment]
Windows is still on 2.38.  Please update.

**Comment by jakirkham** [comment]
Help is welcome 🙂

**Comment by jakirkham** [comment]
This was done for Unix in PR ( https://github.com/conda-forge/graphviz-feedstock/pull/32 ). As a few releases have since been made, closing this out in favor of issue ( https://github.com/conda-forge/graphviz-feedstock/issues/46 ) (the more recent release).
