### ISSUE TITLE
sfdp Error: remove_overlap: Graphviz not built with triangulation library

### ISSUE THREAD

**Issue by peterjc** [conda-forge/graphviz-feedstock#31]
New test case, could be added to the recipe:

```
$ sfdp -Tpdf -o sample.pdf sample.dot
Error: remove_overlap: Graphviz not built with triangulation library
```

For reference, my setup:

```
$ conda list | grep graphviz
graphviz                  2.38.0            hf68f40c_1011    conda-forge
python-graphviz           0.10.1                   pypi_0    pypi
```

Apparently Graphviz was not built with the GTS library (Gnu Triangulated Surface Library) or the Triangulation library.

See also: https://gitlab.com/graphviz/graphviz/issues/1269 aka https://gitlab.com/graphviz/graphviz/issues/1269

In the ``build.sh`` we could be doing ``./configure --with-gts=yes ...`` but GTS is not in Conda yet.

I am unclear which triangulation library they are referring to as the other alternative dependency.

**Comment by jakirkham** [comment]
Would you be willing to add an issue to staged-recipes requesting GTS be added?

**Comment by jakirkham** [comment]
Could someone please retest this? Believe PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 ) may have fixed this issue

**Comment by jakirkham** [comment]
Going to tentatively close as PR adds GTS. So believe that's all we need, but please reopen if not

**Comment by peterjc** [comment]
I'd have added the test case, and that may still be worth adding - but good to know this should work in principle... thanks!

**Comment by jakirkham** [comment]
Feel free to submit a PR adding the test.

We do have one with `dot` fwiw. So if that's not quite enough, it should be easy to tweak to cover this use case.

https://github.com/conda-forge/graphviz-feedstock/blob/ea9b5b3418d0a7e4d4117414617d93b988450a8c/recipe/run_test.sh#L13
