### ISSUE TITLE
All graphviz uploads for Windows are of 32 bit

### ISSUE THREAD

**Issue by nehaljwani** [conda-forge/graphviz-feedstock#33]
All uploaded graphviz package tarballs are present in the win-64 subdir, but contain 32 bit DLLs, which is bad/misleading/contradiction. 

I think we should strive to mark them broken or repackage them for win-32 and create proper win-64 packages. Maybe re-package https://github.com/mahkoCosmo/GraphViz_x64/blob/master/graphviz-2.38_x64.tar.gz ?

**Comment by jamesmyatt** [comment]
Why can't the conda-forge build compile the win-64 versions of the files? If someone has compiled them on a PC, then it must be possible to get conda-forge to do it.

**Comment by jakirkham** [comment]
Would you be interested in submitting a PR, @jamesmyatt?

**Comment by jamesmyatt** [comment]
I'd love to but I think it'd take me a while to get it working, if I can even find the time.

**Comment by jakirkham** [comment]
I think that more or less describes the state of affairs here. No one objects to this work happening, but no one has the time to do it. Chances are this will get better when there is a release of code that uses a CMake build process on Windows, but it hasn't happened yet.

**Comment by jakirkham** [comment]
Is this fixed with PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 ) @nehaljwani ? 🙂

**Comment by nehaljwani** [comment]
Indeed. Closing!
