### ISSUE TITLE
Compile with librsvg

### ISSUE THREAD

**Issue by jakobandersen** [conda-forge/graphviz-feedstock#53]
It would be great if you could add ``librsvg`` to the host and run requirements.
This is needed for Graphviz to be able to, for example, make graphs where SVG images are used as node images while rendering to PDF.

**Comment by jakirkham** [comment]
A PR would be welcome 😀

**Comment by Nojgaard** [comment]
Getting this pull request accepted would be really be great, as I am depending on librsvg for graphviz too.

I made the same pull request in August (#48), but have not heard of any update.

**Comment by jakobandersen** [comment]
Great, thanks!
(PR #48 and #54 are then obsolete)
