### ISSUE TITLE
Updated versions

### ISSUE THREAD

**Issue by jarrodmillman** [conda-forge/graphviz-feedstock#55]
@jjhelmus, @jakirkham I am a core developer of NetworkX and pygraphviz.  We keep getting bug reports from users trying to install pygraphviz with conda.  It looks like you've stopped providing recent versions for Windows and your Mac build is failing.

Is there anything I can do to help?

**Comment by jakirkham** [comment]
For clarity Travis CI is used for `ppc64le` these days. It seemed to have just timed out. So [restarted it]( https://travis-ci.com/github/conda-forge/graphviz-feedstock/builds/189531783 ).

**Comment by jakirkham** [comment]
Generally yes we would welcome any help from the broader community that folks are able to offer.

Windows builds have been a pain point historically. We have been repackaging binaries from upstream since we have had difficulty building from source historically. So have been somewhat constrained on upstream for releases there.

Ideally we would build from source on Windows as we do on other platforms, which would really help not all stay on top of releases, but improve the end user experience. They added CMake support relatively recently, but no one has had time to explore this. Building from source with CMake seems like a good path forward from a maintenance perspective ( https://github.com/conda-forge/graphviz-feedstock/issues/11 ).

Is this something you would be willing to help with?

**Comment by jarrodmillman** [comment]
Graphviz provides Windows binaries for 2.44.1 and has improved the Windows build/deployment process:
https://github.com/conda-forge/graphviz-feedstock/issues/47#issuecomment-678573590

Maybe we could start by updating to 2.44.1 (https://github.com/conda-forge/graphviz-feedstock/issues/46) and just repackaging the prebuilt Windows binaries.  Then we could tackle building from source later.  I am busy working on the NetworkX 2.6 release as well as my own work, so I am not sure I can commit to sorting out building Windows binaries at the moment (I don't use Windows).  Is there any reason that we can't use the prebuilt Windows binaries at least for one release?

I've never used conda (I always use pip) and am not familiar with how to contribute.  I can look into reenabling using the prebuilt Windows binaries.  Do you know the commit where it was disabled?  I cloned the project and searched the commit messages for the word Windows, which only found this:
| * 081a03b - Make the license file easy to find on Windows (3 years, 2 months ago) [John Kirkham]
That modified ``recipe/bld.bat``.  I can't figure out what used to call that.  I couldn't find it in the history of the travis, cirlce-ci, azure, or GH actions config files.

Are there any developer guides for contributing?  Or could you point me to where I should look?

Also is it possible to update these from here:
- https://anaconda.org/anaconda/graphviz
- https://anaconda.org/anaconda/pygraphviz

Or does that involve a different process?

Also do you know why there aren't Windows packages for pygraphviz:
https://github.com/conda-forge/pygraphviz-feedstock/issues/13
Is that just due to this issue?  Or does additional work need to be done there?

**Comment by jarrodmillman** [comment]
After poking around a bit more, I found this:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

GraphViz 2.40 has bugs in the cgraph portion of the library, which makes it not work for pygraphviz.  And we no longer support GraphViz 2.38.  Do we need to also modify this repo?  Is there a list of what repos need to be edited and how the work together?

**Comment by jakirkham** [comment]
Yep that sounds like a reasonable starting point.

Would start by forking the repo, making a PR that [drops this line]( https://github.com/conda-forge/graphviz-feedstock/blob/bf95e492d43b197362ea2b205a0a1be9f86225f3/recipe/meta.yaml#L14 ), and asking the bot to re-render (the PR template explains how to do this). Then wait to see what happens on CI.

All of [our docs live here]( https://conda-forge.org/docs/ ). Also here is [the maintainer documentation]( https://conda-forge.org/docs/maintainer/00_intro.html ).

We usually work with Anaconda to try and stay in sync. Starting with a PR here is good way to get that process going.

Eventually yes we will want to update the pinnings, but let's start with getting new builds up here and we can follow up on that afterwards.

Thanks for your help here! 😄 Please let us know if you have any other questions 🙂

**Comment by jakirkham** [comment]
Moved to 2.46.1 in PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 ). Also building Windows from source! 😀

**Comment by jsignell** [comment]
We are running into some issues in the dask test suite on windows. Seems like it is probably related to this change. https://github.com/dask/dask/issues/7231
