### ISSUE TITLE
spaCy and graphviz in contras

### ISSUE THREAD

**Issue by VasilijKolomiets** [conda-forge/graphviz-feedstock#66]
I did [issue](https://github.com/conda-forge/graphviz-feedstock/issues/65).   And now I see that or `conda install conda-forge::python-graphviz conda-forge::graphviz=2.46.1`  or` conda install -c conda-forge spacy`.

Never together )))

Windows10
AMD
conda with Python 3.8
Jupiter script installed

**Comment by jakirkham** [comment]
Please share a `conda create` command showing the issue with a fresh environment. Also please feel out the rest of the issue template

**Comment by VasilijKolomiets** [comment]
The right way is to install 1-st spaCy and NLTK. 2-nd pytorch and only 3-d  graphviz.  This way all is Ok.      
If 1-st step is installing  graphviz - than You cant install spaCy.

**Comment by VasilijKolomiets** [comment]
> Please share a `conda create` command showing the issue with a fresh environment. Also please feel out the rest of the issue template

**Comment by VasilijKolomiets** [comment]
I install by Anaconda (win64) Windows10:
1) switch to conda-forge chanall 
2) install `nltk, spaCy, cupy,  scikit-learn,  scikit-image,  matplotlib, numpy, jupyter`  -  just marking squares in Anaconda like that:

![Ana_picking_2021-03-06 150307](https://user-images.githubusercontent.com/12198653/110207579-27506200-7e8d-11eb-8b74-4acf69608ffe.png)

3) install pytorch:  `conda install pytorch torchvision torchaudio torchtext cudatoolkit=10.1 -c pytorch`.   Really installed pytorch 1.8

4) python -m spacy download en_core_web_trf
    python -m spacy download ru_core_news_lg

And all is Ok. Next step fails:

 5)  conda install python-graphviz graphviz=2.46.1
 
 I receive conflict error:

[error.txt](https://github.com/conda-forge/graphviz-feedstock/files/6095351/error.txt)
so for last step I cant reach ))

 6)  pip install torchviz
